[color-theme]
name = 'NeoNight'
color-preference = 'dark'

[color-theme.base]
black = '#282C34'
blue = '#5e72f7'
cyan = '#56B6C2'
green = '#3acf5f'
grey = '#3E4451'
magenta = '#C678DD'
orange = '#D19A66'
purple = '#C678DD'
red = '#E06C75'
white = '#ABB2BF'
yellow = '#E5C07B'

[color-theme.syntax]
attribute = '$yellow'
builtinType = '$cyan'
comment = '#5C6370'
constant = '$yellow'
constructor = '$yellow'
embedded = '$cyan'
enum = '$yellow'
enum-member = '$red'
enumMember = '$red'
escape = '$cyan'
field = '$grey'
function = '#4ec2fc'
"function.method" = '$blue'
interface = '$yellow'
keyword = '$blue'
"keyword.control" = '$purple'
method = '#4ec2fc'
number = '$yellow'
property = '$blue'
"punctuation.delimiter" = '$yellow'
selfKeyword = '$purple'
string = '#47ad51'
"string.escape" = '$cyan'
struct = '$yellow'
structure = '$yellow'
symbol = '$yellow'
tag = '$blue'
"text.reference" = '$yellow'
"text.title" = '$orange'
"text.uri" = '$cyan'
type = '$yellow'
"type.builtin" = '$cyan'
typeAlias = '$yellow'
variable = '$red'
"variable.other.member" = '$red'

[color-theme.ui]
"activity.background" = '#21252B'
"activity.current" = '$black'
"completion.background" = '#21252B'
"completion.current" = '#2C313A'
"completion_lens.foreground" = '#5C6370'
"debug.breakpoint" = '$red'
"debug.breakpoint.hover" = '#E06C7566'
"editor.background" = '#212124'
"editor.caret" = '#528BFF'
"editor.current_line" = '#2C313C'
"editor.debug_break_line" = '#528abF37'
"editor.dim" = '#5C6370'
"editor.drag_drop_background" = '#79c1fc55'
"editor.drag_drop_tab_background" = '#0b0e1455'
"editor.focus" = '#CCCCCC'
"editor.foreground" = '$white'
"editor.indent_guide" = '$grey'
"editor.link" = '$blue'
"editor.selection" = '$grey'
"editor.sticky_header_background" = '$black'
"editor.visible_whitespace" = '$grey'
"error_lens.error.background" = '#E06C7520'
"error_lens.error.foreground" = '$red'
"error_lens.other.background" = '#5C637020'
"error_lens.other.foreground" = '#5C6370'
"error_lens.warning.background" = '#302e25'
"error_lens.warning.foreground" = '#e69749'
"hover.background" = '#21252B'
"inlay_hint.background" = '#528abF37'
"inlay_hint.foreground" = '$white'
"lapce.border" = '#000000'
"lapce.button.primary.background" = '#50a14f'
"lapce.button.primary.foreground" = '$black'
"lapce.dropdown_shadow" = '#000000'
"lapce.error" = '$red'
"lapce.icon.active" = '$white'
"lapce.icon.inactive" = '#5C6370'
"lapce.plugin.author" = '#B0B0B0'
"lapce.plugin.description" = '$white'
"lapce.plugin.name" = '#DDDDDD'
"lapce.remote.connected" = '#50A14F'
"lapce.remote.connecting" = '#C18401'
"lapce.remote.disconnected" = '#E45649'
"lapce.remote.icon" = '$black'
"lapce.remote.local" = '#4078F2'
"lapce.scroll_bar" = '#3E4451BB'
"lapce.tab.active.background" = '$black'
"lapce.tab.active.foreground" = '$white'
"lapce.tab.active.underline" = '#528BFF'
"lapce.tab.inactive.background" = '#21252b'
"lapce.tab.inactive.foreground" = '$white'
"lapce.tab.inactive.underline" = '#528BFF77'
"lapce.tab.separator" = ''
"lapce.warn" = '$magenta'
"markdown.blockquote" = '#898989'
"palette.background" = '#21252B'
"palette.current.background" = '#2C313A'
"palette.current.foreground" = '$white'
"palette.foreground" = '$white'
"panel.background" = '#121417'
"panel.current.background" = '#2C313A'
"panel.current.foreground" = '$white'
"panel.current.foreground.dim" = '#5C6370'
"panel.foreground" = '$white'
"panel.foreground.dim" = '#5C6370'
"panel.hovered.active.background" = '#5C6370'
"panel.hovered.background" = '#343A45'
"panel.hovered.foreground" = '$white'
"panel.hovered.foreground.dim" = '#5C6370'
"source_control.added" = '#50A14FCC'
"source_control.modified" = '#0184BCCC'
"source_control.removed" = '#FF5266CC'
"status.background" = '#21252B'
"status.foreground" = '$white'
"status.modal.insert.background" = '$red'
"status.modal.insert.foreground" = '$black'
"status.modal.normal.background" = '$blue'
"status.modal.normal.foreground" = '$black'
"status.modal.terminal.background" = '$purple'
"status.modal.terminal.foreground" = '$black'
"status.modal.visual.background" = '$yellow'
"status.modal.visual.foreground" = '$black'
"terminal.background" = '$black'
"terminal.black" = '$black'
"terminal.blue" = '$blue'
"terminal.bright_black" = '#545862'
"terminal.bright_blue" = '$blue'
"terminal.bright_cyan" = '$cyan'
"terminal.bright_green" = '$green'
"terminal.bright_magenta" = '$magenta'
"terminal.bright_red" = '$red'
"terminal.bright_white" = '#C8CCD4'
"terminal.bright_yellow" = '$yellow'
"terminal.cursor" = '$white'
"terminal.cyan" = '$cyan'
"terminal.foreground" = '$white'
"terminal.green" = '$green'
"terminal.magenta" = '$magenta'
"terminal.red" = '$red'
"terminal.white" = '$white'
"terminal.yellow" = '$yellow'

[ui]
drop-shadow-width = 4
font-size = 15
header-height = 35
hover-font-size = 0
icon-size = 0
list-line-height = 25
preview-editor-width = 0
scroll-width = 10
status-height = 25
tab-close-button = 'Right'
tab-min-width = 100
trim-search-results-whitespace = true